# Generated by Django 5.2.10 on 2026-02-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name="Ім'я категорії")),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='Зображення')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('views', models.IntegerField(default=0, verbose_name='Перегляди')),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукти',
                'verbose_name_plural': 'Продукти',
                'ordering': ['-created_at'],
            },
        ),
    ]
